/// Integration tests for the Horn slope kernel.
///
/// Synthetic fixtures (flat, ramp_ew):
///   Generated by testdata/regenerate.sh using gdaldem as ground truth.
///   Unit scale (inv=1.0) — isolates kernel arithmetic from Mercator correction.
///   To regenerate: cd testdata && bash regenerate.sh
///
/// Real-terrain fixture (buachaille):
///   Buachaille Etive Mòr, z=12 x=1992 y=1261, Terrarium source.
///   Generated by testdata/gen_buachaille_ref.py with correct Mercator
///   georeferencing (ground_res = ewres * cos(lat_center) ≈ 10.5 m/px at 56.7°N).
///   Exercises the full pipeline: real elevation data + Mercator correction.
///   To regenerate: cd testdata && python3 gen_buachaille_ref.py
use slope_server::slope::{horn_kernel, mercator_scale_factors};

const TILE: usize = 16;
const PAD: usize = TILE + 2; // 18

fn load_f32(path: &str) -> Vec<f32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    assert!(
        bytes.len() % 4 == 0,
        "{path} size not divisible by 4: {}",
        bytes.len()
    );
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect()
}

fn fixture(name: &str) -> String {
    // Fixtures live in testdata/ relative to the workspace root.
    format!(
        "{}/testdata/{name}",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn run_horn_on_padded(padded: &[f32], inv_ew: f32, inv_ns: f32) -> Vec<f32> {
    let mut out = Vec::with_capacity(TILE * TILE);
    for row in 0..TILE {
        for col in 0..TILE {
            let pr = row;
            let pc = col;
            let win = [
                padded[pr * PAD + pc],
                padded[pr * PAD + pc + 1],
                padded[pr * PAD + pc + 2],
                padded[(pr + 1) * PAD + pc],
                padded[(pr + 1) * PAD + pc + 1],
                padded[(pr + 1) * PAD + pc + 2],
                padded[(pr + 2) * PAD + pc],
                padded[(pr + 2) * PAD + pc + 1],
                padded[(pr + 2) * PAD + pc + 2],
            ];
            out.push(horn_kernel(win, inv_ew, inv_ns));
        }
    }
    out
}

#[test]
fn flat_dem_zero_slope() {
    let padded = load_f32(&fixture("flat.bin"));
    assert_eq!(padded.len(), PAD * PAD);

    let reference = load_f32(&fixture("flat_slopes.bin"));
    assert_eq!(reference.len(), TILE * TILE);

    let computed = run_horn_on_padded(&padded, 1.0, 1.0);

    for (i, (&got, &expected)) in computed.iter().zip(reference.iter()).enumerate() {
        let diff = (got - expected).abs();
        assert!(
            diff < 1e-4,
            "pixel {i}: got {got}°, expected {expected}°, diff {diff}°"
        );
    }
}

#[test]
fn ew_ramp_45_degrees() {
    let padded = load_f32(&fixture("ramp_ew.bin"));
    assert_eq!(padded.len(), PAD * PAD);

    let reference = load_f32(&fixture("ramp_ew_slopes.bin"));
    assert_eq!(reference.len(), TILE * TILE);

    let computed = run_horn_on_padded(&padded, 1.0, 1.0);

    let mut max_diff = 0.0f32;
    for (i, (&got, &expected)) in computed.iter().zip(reference.iter()).enumerate() {
        let diff = (got - expected).abs();
        max_diff = max_diff.max(diff);
        assert!(
            diff < 1e-4,
            "pixel {i}: got {got}°, expected {expected}°, diff {diff}°"
        );
    }

    // The ramp rises 1 unit/px E-W, so every pixel should be exactly 45°.
    for (i, &got) in computed.iter().enumerate() {
        assert!(
            (got - 45.0).abs() < 1e-4,
            "pixel {i}: expected 45°, got {got}°"
        );
    }

    eprintln!("max diff vs reference: {max_diff:.2e}°");
}

#[test]
fn buachaille_etive_mor_vs_gdaldem() {
    // Real Terrain-RGB tile: Buachaille Etive Mòr, z=12 x=1992 y=1261.
    // Reference slopes produced by gdaldem with correct Mercator georeferencing.
    // Validates both kernel correctness and Mercator scale correction on real data.
    const Z: u32 = 12;
    const CY: u32 = 1261;
    const REAL_TILE: usize = 512;
    const REAL_PAD: usize = REAL_TILE + 2;

    let padded = load_f32(&fixture("buachaille_padded.bin"));
    assert_eq!(padded.len(), REAL_PAD * REAL_PAD, "padded buffer wrong size");

    let reference = load_f32(&fixture("buachaille_slopes.bin"));
    assert_eq!(reference.len(), REAL_TILE * REAL_TILE, "reference slopes wrong size");

    // Use the same scale factors our server would use for this tile.
    let (inv_ew, inv_ns) = mercator_scale_factors(Z, CY, REAL_TILE as u32);

    // Run the Horn kernel over the center 512×512 region.
    let mut computed = Vec::with_capacity(REAL_TILE * REAL_TILE);
    for row in 0..REAL_TILE {
        for col in 0..REAL_TILE {
            let win = [
                padded[ row      * REAL_PAD + col    ],
                padded[ row      * REAL_PAD + col + 1],
                padded[ row      * REAL_PAD + col + 2],
                padded[(row + 1) * REAL_PAD + col    ],
                padded[(row + 1) * REAL_PAD + col + 1],
                padded[(row + 1) * REAL_PAD + col + 2],
                padded[(row + 2) * REAL_PAD + col    ],
                padded[(row + 2) * REAL_PAD + col + 1],
                padded[(row + 2) * REAL_PAD + col + 2],
            ];
            computed.push(horn_kernel(win, inv_ew, inv_ns));
        }
    }

    let mut max_diff = 0.0f32;
    let mut sum_diff = 0.0f64;
    for (i, (&got, &expected)) in computed.iter().zip(reference.iter()).enumerate() {
        let diff = (got - expected).abs();
        max_diff = max_diff.max(diff);
        sum_diff += diff as f64;
        assert!(
            diff < 0.5,
            "pixel {i} (row={}, col={}): got {got:.4}°, expected {expected:.4}°, diff {diff:.4}°",
            i / REAL_TILE, i % REAL_TILE,
        );
    }
    let mean_diff = sum_diff / (REAL_TILE * REAL_TILE) as f64;
    eprintln!("buachaille vs gdaldem: max_diff={max_diff:.4}° mean_diff={mean_diff:.4}°");
}
